# Input columns:
MARKER cpaid
ALLELE EFFECT_ALLELE NON_EFFECT_ALLELE
EFFECT BETA
STDERRLABEL SE
FREQLABEL EAF
PVALUE PVAL
STRAND STRAND
CUSTOMVARIABLE N
LABEL N AS N
SCHEME STDERR
WEIGHT N
USESTRAND ON
AVERAGEFREQ ON
MINMAXFREQ ON
VERBOSE OFF
GENOMICCONTROL ON

PROCESS /genetics/MixedStudies/Projects/2211_cIMT_GWAMA_PHRI/Results/GWAS/CHCP/Cleaned/OAD/EUR/maxRCF/CLEANED.CP_cIMT.maxRCF.OAD.W.noBMI.EUR.KL.230922.cpaid.gz
PROCESS /genetics/MixedStudies/Projects/2211_cIMT_GWAMA_PHRI/Results/GWAS/NFBC/Cleaned/maxLCF/CLEANED.EGG_cIMT.maxLCF.OAD.W.noBMI.NFBC1966.EUR.JR.230801.cpaid.gz
PROCESS /genetics/MixedStudies/Projects/2211_cIMT_GWAMA_PHRI/Results/GWAS/UKB/Cleaned/BRIT/maxIMT240_2/240916/CLEANED.EGG_cIMT.OAD.maxIMT240_2.W.noBMI.UKB.BRIT.AL.240916.cpaid.gz


ANALYZE HETEROGENEITY

OUTFILE /genetics/MixedStudies/Projects/2211_cIMT_GWAMA_PHRI/Results/GWAMA/OAD/EUR/maxIMT/W/240926_maxIMT_OAD_EUR_W_noBMI_GWAMA.TBL
