# Input columns:
MARKER cpaid
ALLELE EFFECT_ALLELE NON_EFFECT_ALLELE
EFFECT BETA
STDERRLABEL SE
FREQLABEL EAF
PVALUE PVAL
STRAND STRAND
CUSTOMVARIABLE N
LABEL N AS N
SCHEME STDERR
WEIGHT N
USESTRAND ON
AVERAGEFREQ ON
MINMAXFREQ ON
VERBOSE OFF

GENOMICCONTROL ON
# GENOMICCONTROL LIST /path2reffiles/QTSNPs_AEL_TW.txt

PROCESS //genetics/MixedStudies/Projects/2211_cIMT_GWAMA_PHRI/Results/GWAS/ABCD/Cleaned/CLEANED.EGG_cIMT.maxCCA.ADO.MW.noBMI.EUR.EM.20230626.cpaid.gz
PROCESS //genetics/MixedStudies/Projects/2211_cIMT_GWAMA_PHRI/Results/GWAS/CHCP/Cleaned/CLEANED.CP_cIMT.maxRCF.ADO.MW.noBMI.EUR.KL.230922.cpaid.gz
PROCESS //genetics/MixedStudies/Projects/2211_cIMT_GWAMA_PHRI/Results/GWAS/PANIC/Cleaned/CLEANED.CP_cIMT.meanRCF.ADO.MW.noBMI.EUR.KL.230922.cpaid.gz
PROCESS //genetics/MixedStudies/Projects/2211_cIMT_GWAMA_PHRI/Results/GWAS/GenR/Batch2/Cleaned/CLEANED.EGG_cIMT.maxLCF.CLD.MW.noBMI.GenR.EUR.MMG.231005.cpaid.gz
PROCESS //genetics/MixedStudies/Projects/2211_cIMT_GWAMA_PHRI/Results/GWAS/GenR/Batch1/Cleaned/CLEANED.EGG_cIMT.maxLCF.CLD.MW.noBMI.GenR.EUR.MMG.230912.cpaid.gz
PROCESS //genetics/MixedStudies/Projects/2211_cIMT_GWAMA_PHRI/Results/GWAS/FAMILY/Cleaned/CLEANED.EGG_cIMT.maxIMT.ADO.MW.noBMI.EUR.AL.20240528.cpaid.gz

OUTFILE //genetics/MixedStudies/Projects/2211_cIMT_GWAMA_PHRI/Results/GWAMA/maxIMT_ADO/EGG_CLD_MaxIMT_MW_noBMI_AL_240610.TBL
ANALYZE HETEROGENEITY