# Input columns:
MARKER cpaid
ALLELE EFFECT_ALLELE NON_EFFECT_ALLELE
EFFECT BETA
STDERRLABEL SE
FREQLABEL EAF
PVALUE PVAL
#STRAND STRAND
CUSTOMVARIABLE N
LABEL N AS N
SCHEME STDERR
WEIGHT N
# USESTRAND OFF
AVERAGEFREQ ON
MINMAXFREQ ON
VERBOSE ON
GENOMICCONTROL ON
TRACKPOSITIONS ON
CHROMOSOMELABEL CHR
POSITIONLABEL POS


PROCESS /genetics/MixedStudies/Projects/2211_cIMT_GWAMA_PHRI//Results/GWAS/CHCP/QCed/OAD/maxRCF/EUR/CLEANED.CP_cIMT.maxRCF.OAD.MW.adjBMI.EUR.KL.230922_3.cpaid_noDup_noAFO.tbl.gz
PROCESS /genetics/MixedStudies/Projects/2211_cIMT_GWAMA_PHRI//Results/GWAS/NFBC/QCed/OAD/maxLCF/EUR/CLEANED.EGG_cIMT.maxLCF.OAD.MW.adjBMI.NFBC1966.EUR.JR.230801.cpaid_noDup_noAFO.tbl.gz
PROCESS /genetics/MixedStudies/Projects/2211_cIMT_GWAMA_PHRI//Results/GWAS/GRACE/QCed/OAD/maxLCF/EUR/CLEANED.GRACE_cIMT.maxLCF.OAD.MW.adjBMI.EUR.AL.20240903_tmp.cpaid_noDup_noAFO.tbl.gz
PROCESS /genetics/MixedStudies/Projects/2211_cIMT_GWAMA_PHRI//Results/GWAS/UKB/QCed/OAD/maxIMT240_2/BRIT/CLEANED.EGG_cIMT.OAD.maxIMT240_2.MW.adjBMI.UKB.BRIT.AL.240927_tmp.cpaid_noDup_noAFO.tbl.gz
PROCESS /genetics/MixedStudies/Projects/2211_cIMT_GWAMA_PHRI//Results/GWAS/ALSPAC/QCed/OAD/maxLCF/EUR/CLEANED.ALSPAC_cIMT.maxLCF.OAD.MW.adjBMI.EUR.AL.20240702_3.cpaid_noDup_noAFO.tbl.gz
PROCESS /genetics/MixedStudies/Projects/2211_cIMT_GWAMA_PHRI//Results/GWAS/UKB/QCed/OAD/maxIMT240_2/NBEUR/CLEANED.EGG_cIMT.OAD.maxIMT240_2.MW.adjBMI.UKB.NBEUR.AL.240927_tmp.cpaid_noDup_noAFO.tbl.gz
PROCESS /genetics/MixedStudies/Projects/2211_cIMT_GWAMA_PHRI//Results/GWAS/FAMILY/QCed/OAD/maxLCF/EUR/CLEANED.FAMILY_cIMT.maxLCF.OAD.MW.adjBMI.EUR.AL.20240825_2.cpaid_noDup_noAFO.tbl.gz

OUTFILE /genetics/MixedStudies/Projects/2211_cIMT_GWAMA_PHRI//Results/GWAMA/OAD/EUR/maxLCFp/adjBMI/241023_maxLCFp_OAD_EUR_MW_adjBMI_GWAMA_noAFO .TBL
ANALYZE HETEROGENEITY
